# Generated by Django 5.2.17 on 2026-10-03 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(help_text='Person currently holding the role', max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('responsibilities', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.PositiveIntegerField(unique=True)),
                ('shift_label', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('starting_point', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('stops', models.JSONField(default=list, help_text='Ordered list of stop names')),
                ('verified', models.BooleanField(default=True)),
                ('notes', models.JSONField(blank=True, default=list, help_text='List of data-quality note strings')),
            ],
            options={
                'ordering': ['departure_time', 'route_id'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Campuses',
            },
        ),
        migrations.CreateModel(
            name='ChatbotChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.SlugField(max_length=100, unique=True)),
                ('chunk_type', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(help_text='Exact text shown to the user — keep this self-contained and accurate')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Roman Urdu / English phrasings for matching')),
                ('source', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_id', models.SlugField(max_length=80, unique=True)),
                ('category', models.CharField(default='faq', max_length=60)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('verified', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('expires_on', models.DateField(blank=True, help_text='For time-bound answers, e.g. an event date', null=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'question'],
            },
        ),
        migrations.CreateModel(
            name='FeeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('morning_semesters', models.JSONField(blank=True, default=list, help_text='List of per-semester fees (PKR)')),
                ('morning_total', models.PositiveIntegerField(blank=True, null=True)),
                ('afternoon_semesters', models.JSONField(blank=True, default=list)),
                ('afternoon_total', models.PositiveIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_type', models.CharField(choices=[('library', 'Library'), ('medical', 'Medical Center'), ('transport', 'Transport Department'), ('scholarships', 'Scholarships & Financial Aid'), ('qec', 'Quality Enhancement Cell'), ('faculty_hostel', 'Faculty Hostel'), ('admission', 'Admission / Info Office'), ('other', 'Other')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, help_text='Short about-us style summary')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Raw phone as given by the source', max_length=30)),
                ('phone_local', models.CharField(blank=True, max_length=20)),
                ('phone_intl', models.CharField(blank=True, max_length=20)),
                ('hours', models.CharField(blank=True, max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('verified', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, help_text='Data-quality note, e.g. conflicting source info')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Service-specific extras: facilities list, booking_process, messages, etc.')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='University of Layyah', max_length=255)),
                ('short_name', models.CharField(default='UL', max_length=20)),
                ('website_domain', models.CharField(default='ul.edu.pk', max_length=100)),
                ('admission_portal_url', models.URLField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('goals', models.JSONField(blank=True, default=list, help_text='List of goal strings')),
            ],
            options={
                'verbose_name': 'University Profile',
                'verbose_name_plural': 'University Profile',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='campusinfo.faculty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('original_name', models.CharField(blank=True, help_text='Name as it appeared in the raw source', max_length=200)),
                ('program_type', models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('Post-ADP', 'Post-ADP'), ('Diploma', 'Diploma'), ('Professional Degree', 'Professional Degree')], max_length=30)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('eligibility', models.TextField(blank=True)),
                ('merit_formula', models.CharField(blank=True, max_length=200)),
                ('shifts', models.JSONField(blank=True, default=list, help_text='e.g. ["Morning", "Afternoon"]')),
                ('fee_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('needs_confirmation', 'Needs Confirmation'), ('conflict', 'Source Conflict'), ('suspicious', 'Suspicious / Likely Wrong')], default='confirmed', max_length=30)),
                ('verified', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='campusinfo.department')),
                ('fee_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='campusinfo.feegroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleStaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='campusinfo.administrationrole')),
            ],
        ),
    ]
